# -----------------------------------------------------------------------
# This is the file that Travis CI looks for to test builds. It tells
# Travis what to do before and after running tests, as well as how to
# run the tests.
#
# Typically, this file should not be modified.
# -----------------------------------------------------------------------
 language: android
 jdk: oraclejdk8
 sudo: false

 env:
  global:
  - ANDROID_API=27
  - ANDROID_BUILD_TOOLS=27.0.1

 android:
   components:
     - tools
     - platform-tools
     - build-tools-$ANDROID_BUILD_TOOLS
     - android-$ANDROID_API
     - extra-google-m2repository

   licenses:
        - android-sdk-preview-license-.+
        - android-sdk-license-.+
        - google-gdk-license-.+

 before_cache:
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

 cache:
  directories:
  - $HOME/.gradle/caches/
  - $HOME/.gradle/daemon      #Cache daemon logs
  - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
  - $HOME/.gradle/wrapper     #Cache the gradle
  - $HOME/.android/build-cache

 before_install:
     - chmod +x gradlew
     - yes | sdkmanager "platforms;android-27"

 script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew assemble
    - ./gradlew check
    - ./gradlew build jacocoTestReport
 after_success:
    - bash <(curl -s https://codecov.io/bash) -t f20cccfd-5333-476f-9485-5614cbda84ee || echo "Codecov did not collect coverage reports"



