# -----------------------------------------------------------------------
# This is the file that Travis CI looks for to test builds. It tells
# Travis what to do before and after running tests, as well as how to
# run the tests.
#
# Typically, this file should not be modified.
# -----------------------------------------------------------------------
 language: android
 jdk: oraclejdk8
 sudo: false

 before_cache:
   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:

 cache:
   directories:
     - $HOME/.gradle/caches/
     - $HOME/.gradle/daemon      #Cache daemon logs
     - $HOME/.gradle/native      #Cache library downloaded from the gradle dependency
     - $HOME/.gradle/wrapper     #Cache the gradle
     - $HOME/.android/build-cache

 addons:
   apt_packages:
     - pandoc
   artifacts:
     paths:
       - $(git ls-files -o | grep build/outputs | tr "\n" ":")

 android:
   components:
     - tools
     - platform-tools
     - build-tools-27.0.1
     - android-27
     - extra-google-m2repository

 before_install:
    - chmod +x gradlew
    - yes | sdkmanager "platforms;android-27"
    - pip install --user codecov

 script:
    - echo "Travis branch is $TRAVIS_BRANCH"
    - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
    - ./gradlew assemble
    - ./gradlew check

 after_success:
    - codecov

 after_failure:
    - pandoc build/reports/tests/index.html -t plain | sed -n '/^Failed tests/,/default-package/p'

 after_script:
    - for f in build/outputs/lint-results.html; do pandoc $f -t plain; done
    - for f in build/outputs/lint-results.html; do pandoc $f -t plain; done


